export const TOGGLE_FAVORITES = "CONTENT/TOGGLE_FAVORITES";
export const GET_MOVIES = "CONTENT/GET_MOVIES";
export const GET_MOVIES_SUCCESS = "CONTENT/GET_MOVIES_SUCCESS";
export const GET_MOVIES_ERROR = "CONTENT/GET_MOVIES_ERROR";
