export const SET_TOKEN = "SET_TOKEN";
export const SET_TOKEN_SUCCESS = "SET_TOKEN_SUCCESS";
export const SET_TOKEN_ERROR = "SET_TOKEN_ERROR";
export const DELETE_TOKEN_DATA = "DELETE_TOKEN_DATA";
export const DELETE_TOKEN_ERROR = "DELETE_TOKEN_ERROR";
